### ISSUE TITLE
Dojo 6: widget-core to core

### ISSUE THREAD

**Issue by nicknisi** [dojo/cli-upgrade-app#34]
dojo/framework/widget-core has been moved into dojo/framework/core. Add a new upgrade to this tool to help facilitate this change.

**Changes**

- all of `d` and `tsx` are now exported from `vdom`. The only exception being `decorate` method from `d` is now in `core/util`
- widget-core is now in core

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/cli-upgrade-app/pull/36
