### ISSUE TITLE
Hangs on Windows

### ISSUE THREAD

**Issue by devpaul** [dojo/cli-upgrade-app#37]
`@dojo/cli-upgrade-app` appears to hang when used on Windows. This was initially reported to me by a customer whose app didn't update and made the updates manually. Most recently I ran into this issue when attempting to update https://github.com/devpaul/catsvsdogs/releases/tag/v1.0 to Dojo 5. The upgrade did work when using WSL, but not when running directly on Windows under a command prompt. The CLI also did not break when sent a CTRL + C suggesting a hang.

I'm currently looking into this issue. Will add more detail or a PR as things unfold.

**Comment by devpaul** [comment]
This is what I'm seeing on Windows using the latest

![image](https://user-images.githubusercontent.com/331431/63204735-c44f6e00-c04f-11e9-9c24-d2c8e79093e2.png)

Works OK with `--dry` but hangs when doing a real run. Same failure on e2e.

Noticed that there's an error on build: https://travis-ci.org/dojo/cli-upgrade-app/jobs/550208526#L1555

Don't think it's related, but worth mentioning just to track.

**Comment by devpaul** [comment]
Updating `inquirer` to `6.5.1` has fixed the hang. It now errors out when trying to upgrade packages to Dojo 6.

![image](https://user-images.githubusercontent.com/331431/63205406-b5b98480-c058-11e9-993d-9b303c0f1d74.png)

Fails for both e2e tests and catsvsdogs

**Comment by agubler** [comment]
@devpaul That would be because the dojo packages have not been released on 6.0.0 yet. Once they have been released it should work as expected.

I think updating the inquirer package will resolve the hanging problem.
