### ISSUE TITLE
Tech debt: running multiple migrations and migration structure

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-upgrade-app#6]
The command currently doesn't have any kind of structure for running multiple migrations. The command should be structured better to compartmentalise upgrades between versions, and the command itself should be able to upgrade between multiple versions for example a user going from 2.0.0 -> 4.0.0

**Comment by aciccarello** [comment]
I've gotten this partially completed in a branch on my fork. It currently just reruns the v3 transforms though checking the package.json should be implemented in the future.
